<nav>

<ul id="menu-demo2">
	<li><a href="http://www.genealexis.fr/index.php">Le Blog</a></li>
	<li><a href="http://www.genealexis.fr/cartes-postales/index.php">Terres d'ancêtres</a></li>
	<li><a href="http://www.genealexis.fr/genealogie/index.php">Ma généalogie</a>
		<ul>
			<li><a href="http://www.genealexis.fr/genealogie/index.php#%23ancetres">Mes ancêtres</a></li>
			<li><a href="http://www.genealexis.fr/genealogie/index.php#%23onomastique">Onomastique</a></li>
			<li><a href="http://www.genealexis.fr/genealogie/index.php#%23genealogies">Autres généalogies</a></li>
			<li><a href="http://www.genealexis.fr/genealogie/index.php#%23dossiers">Dossiers</a></li>
		</ul>
	</li>	
	<li><a href="http://cartespostalesanciennes.genealexis.fr">Cartes postales anciennes</a></li>
	<li><a href="index.php">PubliGED</a></li>
	<li><a href="http://www.genealexis.fr/bibliographie/index.php">Ma bibliothèque généalogique</a></li>
	<li><a href="http://archives.genealexis.fr">Archives</a></li>
</ul>

</nav>

<?php /* include('include/resp.inc'); */ ?>