<div class="Footer">

	<p style="text-align:center;font-size:12px;">
		<a href="http://www.genealexis.fr/divers/mentions.php" title="lire les mentions légales du blog" >Mentions l&eacute;gales</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="http://www.genealexis.fr/index.php/me-contacter.html" title="Cliquez ici pour me contacter">Contact</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="https://twitter.com/alexisamand" title="Cliquez ici pour me suivre sur Twitter">Twitter</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="https://www.facebook.com/genealexis.fr" title="Cliquez ici pour lire la page facebook du site">Facebook</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="https://plus.google.com/117361709952417935347">Google+</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="http://www.genealexis.fr/index.php?format=feed&type=rss">Flux RSS</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="http://cv.genealexis.fr" title="mon CV de webmaster">Mon CV</a>
	</p>
	
	<p style="text-align:center;font-size:10px;">
		&copy; 2009-2021 - Tous droits r&eacute;serv&eacute;s. Reproduction interdite sans autorisation.<br/>
		Site r&eacute;alis&eacute; par <a href="http://www.boitasite.com" title="Création et référencement de sites web">Alexis AMAND</a>	
	<br/>			
	</p>
			
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://www.genealexis.fr/piwik/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "1"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->

<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["setDomains", ["*.publiged.genealexis.fr"]]);
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//www.genealexis.fr/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '10']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//www.genealexis.fr/piwik/piwik.php?idsite=10" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
 
</div>