<div class="sidebar1">

<br><br>

<div id="cadremenu">

<h1 style="background-image:url(images/all.png);background-repeat:no-repeat;padding-left:28px;background-position:left center;">Aider le projet</h1>
<p style="text-align:justify;">PubliGED est sur Tipeee, le premier site français de tip participatif. Cliquez sur l'image rouge ci-dessous pour en savoir plus.</p>
<p style="text-align:center;"><a href="https://www.tipeee.com/genealexis"><img src="images/tipeee.png" width="140px"></a></p>

</div>

<br><br>

<div id="cadremenu">

<h1 style="background-image:url(images/all.png);background-repeat:no-repeat;padding-left:28px;background-position:left center;">PubliGED</h1>

  <ul>
	<li><a href="index.php">Le projet</a></li>
	<li><a href="fonctionnalites.php">Les fonctionnalités</a></li>
	<li><a href="demos.php">Demos</a></li>	
	<li><a href="captures.php">Captures d'écran</a></li>	
	<li><a href="downloads.php">Téléchargements</a></li>
	<li><a href="https://www.tipeee.com/genealexis/">Soutenir le projet</a></li>
	<li><a href="contribub.php">Contributeurs</a>
  </ul>

</div>

<br><br>

<div id="cadremenu">

<h1 style="background-image:url(images/all.png);background-repeat:no-repeat;padding-left:28px;background-position:left center;">Communauté</h1>

  <ul>
	<li><a href="https://www.facebook.com/Publiged/">Le projet sur Facebook</a></li>
	<li><a href="https://github.com/AlexisAmand/PubliGED">Le projet sur GitHub</a></li>
	<li><a href="https://twitter.com/hashtag/PubliGED?src=hashtag_click&f=live">Le projet sur Twitter</a></li>
  </ul>

</div>

<center>
<script async src="http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:inline-block;width:180px;height:150px"
     data-ad-client="ca-pub-1550427609493753"
     data-ad-slot="4433046845"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</center>	

</div>